# Generated by Django 4.1.6 on 2023-02-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('result', models.FloatField(default=0.0)),
                ('response', models.CharField(max_length=200)),
            ],
        ),
    ]
